image: gitlab.ensimag.fr:5050/gl2022/g10/gl54:latest

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - source /home/gl/.bashrc
    - mvn compile

test:
  stage: test
  script:
    - mvn verify

