image: gitlab.ensimag.fr:5050/gl2022/g10/gl54:latest

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - source /home/gl/.bashrc
    - mvn compile
  only: 
    - dev
    - master
    - gitlab-autotests

test:
  stage: test
  script:
    - source /home/gl/.bashrc
    - mvn clean verify
#    - mvn -Djacoco.skip=false -Dmaven.test.failure.ignore clean verify
  only:
    - dev
    - master
    - gitlab-autotests
