image: gitlab.ensimag.fr:5050/gl2022/g10/gl54:latest

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - source /home/gl/.bashrc
    - mvn compile
    - <generate public/unit_tests.svg>
  artifacts:
    paths:
      - public/build.svg
  only: 
    - dev
    - master
    - gitlab-autotests

pages:
  stage: deploy
  trigger: build
  artifacts:
    paths:
    - public
  only:
  - master
